-- USERS tabla feltoltese
INSERT INTO USERS (USER_ID, USER_NAME, EMAIL_ADDRESS, USER_CURRENT_WEIGHT, USER_GOAL_WEIGHT, USER_HEIGHT, USER_AGE, USER_PASSWORD, DAILY_WATER_AMOUNT, CURRENT_WATER_AMOUNT )
	values (1, 'dikomako', 'dittrich.diana88@gmail.com', 60, 54, 160, 30, '$2a$10$pmd0a.vlhRWPIo3DJWTAse6L7FghFv3ieoZOekD6nVxX7dznccgTy', 0, 0);

-- TYPE_OF_CUPS tabla feltoltese
INSERT INTO TYPE_OF_CUPS (CUP_ID, CUP_NAME, CUP_CAPACITY, USER_ID)
	values (1, 'Coca-Cola glass', 330, 1);
INSERT INTO TYPE_OF_CUPS (CUP_ID, CUP_NAME, CUP_CAPACITY, USER_ID)
	values (2, 'Tea cup', 450, 1);
INSERT INTO TYPE_OF_CUPS (CUP_ID, CUP_NAME, CUP_CAPACITY, USER_ID)
	values (3, 'Beer mug', 400, 1);
INSERT INTO TYPE_OF_CUPS (CUP_ID, CUP_NAME, CUP_CAPACITY, USER_ID)
	values (4, 'Mineral water bottle', 1500, 1);